PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS schema_version(version INTEGER PRIMARY KEY CHECK(version=1));
INSERT OR IGNORE INTO schema_version VALUES(1);
CREATE TABLE IF NOT EXISTS config(id INTEGER PRIMARY KEY CHECK(id=1), value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS timer(id INTEGER PRIMARY KEY CHECK(id=1), state TEXT NOT NULL CHECK(state IN ('NOT_STARTED','ACTIVE','PAUSED','ENDED')), started_at TEXT, ended_at TEXT, resumed_at TEXT, elapsed_ms INTEGER NOT NULL DEFAULT 0 CHECK(elapsed_ms>=0));
INSERT OR IGNORE INTO timer(id,state) VALUES(1,'NOT_STARTED');
CREATE TABLE IF NOT EXISTS operators(id INTEGER PRIMARY KEY, username TEXT NOT NULL UNIQUE COLLATE NOCASE, name TEXT NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('Admin','Shop Operator','Trade Operator','Viewer')), active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY, operator_id INTEGER NOT NULL REFERENCES operators(id), expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS teams(id TEXT PRIMARY KEY, number TEXT NOT NULL, name TEXT NOT NULL, project TEXT NOT NULL DEFAULT '', description TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', status TEXT NOT NULL CHECK(status IN ('Active','Inactive')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS members(id INTEGER PRIMARY KEY, team_id TEXT NOT NULL REFERENCES teams(id), name TEXT NOT NULL, contact TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS mitras(id TEXT PRIMARY KEY, name TEXT NOT NULL, contact TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', status TEXT NOT NULL CHECK(status IN ('Active','Inactive','Available','Assigned')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS assignments(team_id TEXT PRIMARY KEY REFERENCES teams(id), mitra_id TEXT NOT NULL REFERENCES mitras(id), assigned_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS components(id TEXT PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL DEFAULT '', description TEXT NOT NULL DEFAULT '', price INTEGER NOT NULL CHECK(price>=0), max_per_team INTEGER CHECK(max_per_team IS NULL OR max_per_team>0), notes TEXT NOT NULL DEFAULT '', status TEXT NOT NULL CHECK(status IN ('Active','Inactive')), initial_quantity INTEGER NOT NULL DEFAULT 0 CHECK(initial_quantity>=0), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT, ref TEXT UNIQUE, kind TEXT NOT NULL CHECK(kind IN ('INITIAL_BALANCE','PURCHASE','TRADE','REFUND','BONUS','PENALTY','MANUAL_ADJUSTMENT','CORRECTION','INVENTORY_ADJUSTMENT')), status TEXT NOT NULL DEFAULT 'COMPLETED' CHECK(status IN ('PENDING','COMPLETED','VOIDED','CORRECTED')), request_key TEXT NOT NULL UNIQUE, request_payload TEXT NOT NULL, operator_id INTEGER NOT NULL REFERENCES operators(id), created_at TEXT NOT NULL, elapsed_ms INTEGER NOT NULL, remaining_ms INTEGER NOT NULL, notes TEXT NOT NULL DEFAULT '', reversal_of INTEGER UNIQUE REFERENCES transactions(id), correction_of INTEGER REFERENCES transactions(id));
CREATE TABLE IF NOT EXISTS bolt_ledger(id INTEGER PRIMARY KEY AUTOINCREMENT, transaction_id INTEGER NOT NULL REFERENCES transactions(id), team_id TEXT NOT NULL REFERENCES teams(id), type TEXT NOT NULL, amount INTEGER NOT NULL CHECK(amount<>0), balance_before INTEGER NOT NULL, balance_after INTEGER NOT NULL, CHECK(balance_after=balance_before+amount));
CREATE TABLE IF NOT EXISTS inventory_movements(id INTEGER PRIMARY KEY AUTOINCREMENT, transaction_id INTEGER NOT NULL REFERENCES transactions(id), component_id TEXT NOT NULL REFERENCES components(id), team_id TEXT REFERENCES teams(id), quantity INTEGER NOT NULL CHECK(quantity<>0), quantity_before INTEGER NOT NULL, quantity_after INTEGER NOT NULL, CHECK(quantity_after=quantity_before+quantity));
CREATE TABLE IF NOT EXISTS purchases(id INTEGER PRIMARY KEY AUTOINCREMENT, ref TEXT UNIQUE, transaction_id INTEGER NOT NULL UNIQUE REFERENCES transactions(id), team_id TEXT NOT NULL REFERENCES teams(id), component_id TEXT NOT NULL REFERENCES components(id), team_name TEXT NOT NULL, component_name TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity>0), unit_price INTEGER NOT NULL CHECK(unit_price>=0), total INTEGER NOT NULL CHECK(total=quantity*unit_price), balance_before INTEGER NOT NULL, balance_after INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS trades(id INTEGER PRIMARY KEY AUTOINCREMENT, ref TEXT UNIQUE, transaction_id INTEGER NOT NULL UNIQUE REFERENCES transactions(id), team_a TEXT NOT NULL REFERENCES teams(id), team_b TEXT NOT NULL REFERENCES teams(id), bolts_a INTEGER NOT NULL CHECK(bolts_a>=0), bolts_b INTEGER NOT NULL CHECK(bolts_b>=0), CHECK(team_a<>team_b));
CREATE TABLE IF NOT EXISTS trade_items(id INTEGER PRIMARY KEY, trade_id INTEGER NOT NULL REFERENCES trades(id), from_team TEXT NOT NULL REFERENCES teams(id), to_team TEXT NOT NULL REFERENCES teams(id), component_id TEXT NOT NULL REFERENCES components(id), component_name TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity>0), UNIQUE(trade_id,from_team,component_id));
CREATE TABLE IF NOT EXISTS refunds(id INTEGER PRIMARY KEY AUTOINCREMENT, transaction_id INTEGER NOT NULL UNIQUE REFERENCES transactions(id), purchase_id INTEGER NOT NULL REFERENCES purchases(id), quantity INTEGER NOT NULL CHECK(quantity>0), total INTEGER NOT NULL CHECK(total>=0));
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT, ref TEXT UNIQUE, created_at TEXT NOT NULL, operator_id INTEGER NOT NULL REFERENCES operators(id), action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, old_value TEXT, new_value TEXT, reason TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS ledger_team ON bolt_ledger(team_id,id);
CREATE INDEX IF NOT EXISTS movement_owner ON inventory_movements(team_id,component_id,id);
CREATE INDEX IF NOT EXISTS transactions_date ON transactions(created_at,id);
CREATE INDEX IF NOT EXISTS purchases_team ON purchases(team_id,id);
CREATE INDEX IF NOT EXISTS trades_teams ON trades(team_a,team_b,id);
CREATE INDEX IF NOT EXISTS assignments_mitra ON assignments(mitra_id);
CREATE INDEX IF NOT EXISTS audit_entity ON audit(entity_type,entity_id,id);
CREATE INDEX IF NOT EXISTS members_team ON members(team_id);
CREATE INDEX IF NOT EXISTS teams_name ON teams(name);
CREATE INDEX IF NOT EXISTS components_name ON components(name);
CREATE TRIGGER IF NOT EXISTS immutable_bolts_update BEFORE UPDATE ON bolt_ledger BEGIN SELECT RAISE(ABORT,'Ledger entries are immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_bolts_delete BEFORE DELETE ON bolt_ledger BEGIN SELECT RAISE(ABORT,'Ledger entries are immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_inventory_update BEFORE UPDATE ON inventory_movements BEGIN SELECT RAISE(ABORT,'Inventory entries are immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_inventory_delete BEFORE DELETE ON inventory_movements BEGIN SELECT RAISE(ABORT,'Inventory entries are immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_audit_update BEFORE UPDATE ON audit BEGIN SELECT RAISE(ABORT,'Audit entries are immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_audit_delete BEFORE DELETE ON audit BEGIN SELECT RAISE(ABORT,'Audit entries are immutable'); END;
